spring:
  servlet:
    multipart:
      #单个数据的大小
      max-file-size: 100MB
      #总数据的大小
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mail:
    host: smtp.163.com
    username: 18810102841@163.com
    password: song123456
    default-encoding: utf-8
    protocol: smtp
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog4?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#日志级别
logging:
  level:
    root: info
    com.bchy: debug
  file: log/blog.log
  
server:
  port: 8895
  
common.avatar: /images/avatar.png